# Generated by Django 4.2.1 on 2023-05-16 11:36

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('user_image', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
