# Generated by Django 4.1.7 on 2023-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcars',
            name='car_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='used_car_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
