# Generated by Django 4.1.7 on 2023-04-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_newcars_car_detail_usedcars_used_car_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcars',
            options={'ordering': ['-exshowroom_price']},
        ),
    ]
