# Generated by Django 4.1.7 on 2023-04-25 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_newcars_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcars',
            options={},
        ),
        migrations.AddField(
            model_name='newcars',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
