# Generated by Django 4.2.1 on 2023-05-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_state_states_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcars',
            name='cities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cities'),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.state'),
        ),
    ]
