# Generated by Django 4.1.7 on 2023-04-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted_on']},
        ),
    ]
